### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by michelboyer** [asishrs/smartthings-ringalarmv2#57]
Hey there, after I log into Ring, it only gives me a blank page and no locations to chose from. Here is my log. Any idea what’s going on?
![C5DD2D80-1B26-4FE2-B21C-66EB41A203A0](https://user-images.githubusercontent.com/49692495/127773911-e5096c64-6324-4c95-88f5-37a6f43bc913.jpeg)

**Comment by asishrs** [comment]
The integration doesn’t work well with new ST app.

**Comment by michelboyer** [comment]
Is there a way to download the classic app? Doesn’t appear in the App Store
anymore.

**Comment by asishrs** [comment]
I don’t think so.

**Comment by chilliwebs** [comment]
I believe this issue is related to my PR https://github.com/asishrs/smartthings-ringalarmv2/pull/58 i was also seeing precondition failed, and when i looked at the CloudWatch logs it was reporting:

runtime error: index out of range [0] with length 0: boundsError
[
{
"path": "github.com/aws/aws-lambda-go@v1.8.1/lambda/function.go",
"line": 27,
"label": "(*Function).Invoke.func1"
}
,
{
"path": "runtime/panic.go",
"line": 679,
"label": "gopanic"
}
,
{
"path": "runtime/panic.go",
"line": 75,
"label": "goPanicIndex"
}
,
{
"path": "work/smartthings-ringalarmv2/smartthings-ringalarmv2/httputil/httputil.go",
"line": 278,
"label": "LocationRequest"
}

**Comment by chilliwebs** [comment]
with the changes I have made I was able to successfully integrate Ring with Smartthings (latest app) as of august 13th 2021

looking at my logs i can see events properly logging and faulted status changing when contacts open ect.  but the app ui is not quite perfect, i can try to play around whit that if i get time

**Comment by asishrs** [comment]
Awesome! Keep me posted

Regards,
Asish

**Comment by Antoine6262** [comment]
> with the changes I have made I was able to successfully integrate Ring with Smartthings (latest app) as of august 13th 2021
> 
> looking at my logs i can see events properly logging and faulted status changing when contacts open ect. but the app ui is not quite perfect, i can try to play around whit that if i get time

I know this is an extremely long shot, but i am trying to install the Ring Alarm Manager on the new ST app for a new Ring set-up (just purchased a new home), and am constantly getting the "having trouble connecting" error.

This thread seems to be the most "current" thread discussing issues with set-up on the new ST app.

I have had the app working at my old home and have the full bridge app running in AWS, I just cant seem to get my ZID to populate in the new app...maybe something with the UI not keeping the password entered from screen to screen...hoping you had some success with solving the issue with the new version of ST app, thanks

**Comment by Nick-Hecht-Logikos** [comment]
Hey @Antoine6262 I feel your pain. because this solution is pretty involved with multiple device handlers and AWS integrations, I would suggest taking a look at the live logging:
https://graph.api.smartthings.com/ide/logs

and look at your AWS logs, I could try to help you but I need to know what errors you're seeing.
if the errors are similar to what I was seeing take a look at this https://github.com/asishrs/smartthings-ringalarmv2/pull/58
and see if your code has that change.

**Comment by Antoine6262** [comment]
> Hey @Antoine6262 I feel your pain. because this solution is pretty involved with multiple device handlers and AWS integrations, I would suggest taking a look at the live logging: https://graph.api.smartthings.com/ide/logs
> 
> and look at your AWS logs, I could try to help you but I need to know what errors you're seeing. if the errors are similar to what I was seeing take a look at this #58 and see if your code has that change.

![image](https://user-images.githubusercontent.com/49416250/149214820-2d47ce77-3ab9-46e6-b44b-a8f295fc8eff.png)

I'm seeing "unable to get token" in the logs and that is the real issue - i get a network error when trying to complete the 2FA log in

![Ring Alarm Manager Network Error](https://user-images.githubusercontent.com/49416250/149216517-b4362ab2-8c9d-4503-bb5b-6db886ff85f0.jpg)

**Comment by Nick-Hecht-Logikos** [comment]
looking at your error it looks like your accessKey is null.  the call to ringGetAccessAndRefreshToken is failing. this is happening during your account login? 

**don't** submit any tokens or auth credentials from your logs (obviously)

but personally, open the live logging and try to authenticate in the app again, and  look for your logs.
ringRequest2FAToken() -> Ring Alarm `https://oauth.ring.com/oauth/token` response data: ${apiResponse.data}

you can see this around line 635 of Ring Alarm Manager.

**once again don't post this log**  but perhaps something is failing when it tries to get the initial ringRequest2FAToken there might be an error message here that helps you

**Comment by Nick-Hecht-Logikos** [comment]
I have not really had time or motivation to work on this much, mostly because I was able to hack it together enough to work. but I can give one more piece of advice.

once I had the run account logged in and the status showed my tokens, I still needed to edit my found devices and change their type from placeholder to the appropriate device type.

**Comment by Antoine6262** [comment]
correct, i am unable to authenticate in the ST app.  I can get a 2FA code via ring (not the way in the app because Safari now requires cookies and the app doesnt seem to allow that, so i have to generate a 2FA code via the mobile app), i enter my Ring email and password (it disappears when i navigate back to the screen btw if that matters), i then go to add my 2FA code and hit "Finish 2FA Setup" and get the network error i posted above.

My hunch is that the ST app is not bringing my password from the previous screen over in order to authenticate my Ring account and provide with the token

I am unable to authenticate in the app....that is where i believe it is getting stuck

I was hoping their was a workaround to get my ZID and/or token and i could add it somewhere else outside of the ST app
