### ISSUE TITLE
Mode change events not triggering alarm state changes

### ISSUE THREAD

**Issue by kolosy** [asishrs/smartthings-ringalarmv2#60]
Hi,

I saw that the repo is no longer maintained, but hoping you can just point me in the right direction here. Running the new Smartthings app + v2 ring alarm. Have been for months with no problems. A few days ago, it stopped arming / disarming the system without any apparent changes on my side. If I arm / disarm through the Ring app, I get a ST notification about the state change so it's still communicating and still has a valid token. No errors in the logs. Can you point me where to look? I'm a dev, I can figure it out from there.

**Comment by asishrs** [comment]
Did you check the SmartThings logs? If there is an API call triggering from the app, you should be able to see errors on the log. The code for setting the status is https://github.com/asishrs/smartthings-ringalarmv2/blob/master/main.go#L129

**Comment by kolosy** [comment]
I did, and didn't see any errors. Then I went and cleared my Ring tokens from the app, and now can't sign back in. The api just keeps saying "Not Acceptable." I'm very confused -- I put the same call into Postman and it works fine.

**Comment by asishrs** [comment]
Thats strange. All api routes are working?

**Comment by Its2loud1** [comment]
Yep, Same here. Looks like the integration is broken.

sorry to hear you won’t be updating this integration. It was always a huge help.  Thanks for your service. 

<img width="546" alt="PNG image" src="https://user-images.githubusercontent.com/49612825/136702494-14dc3496-2a64-4e3a-9174-c8d4352c2264.png">

**Comment by seanpbrandon** [comment]
Two days ago integration broke for me as well.  Getting not acceptable

**Comment by kolosy** [comment]
I traced into the aws code, it’s breaking there. I think ring changed their
api or is blocking us somehow.

**Comment by ricklacy** [comment]
I too am getting the same thing

I also got this from AWS, not sure if it's related. But started after I received the email on 10/12/2021:

You are receiving this message because we identified that your account created or updated or invoked Lambda functions on or after July 1, 2021.

AWS Lambda is extending the capability to track the current state of a function through its lifecycle to all functions [1]. With this change, you may need to update your CLI and/or SDK-based automation workflows around creating and updating functions by adding a check that the function became active before performing additional actions that operate on the function.

Previously, states have been used in two primary use-cases. Firstly, to move the blocking setup of VPC resources out of the path of function invocation. Secondly, to allow the Lambda service to optimize new or updated container images for container-image based functions, also before invocation. By moving this additional work out of the path of the invocation, customers see lower latency and better consistency in their function performance.
Infrastructure as code and deployment automation tools such as AWS CloudFormation, AWS Serverless Application Model (SAM), AWS Cloud Development Kit (CDK), Serverless Framework,Hashicorp Terraform, AWS Chalice and Cloud Custodian already support states.

If you are using these tools and are already on the latest Software Development Kit (SDK), you do not need to take any action, and can stop reading now. If you are using an earlier SDK version, please update to the latest one.

We are rolling out this change over multi-phase periods to allow you to update existing tooling for deploying and managing Lambda functions. You can delay this change for your functions until December 5, 2021. Starting December 6, 2021, the delay mechanism expires and all customers see the Lambda states lifecycle applied during function create or update. Read this blog post [2] to learn about this change, timelines for different phases and a reference example on how to check your function state.

![ring](https://user-images.githubusercontent.com/27033977/138005216-569920c4-b9a2-4dc6-b70d-fe6ba7ed3c56.JPG)

**Comment by kolosy** [comment]
Interesting. That reads like a change around management tooling, not actual execution. But the timing is suspicious for sure.

**Comment by asishrs** [comment]
That change won’t impact the API. I think the real issue is some kind of API end point change at Ring side.

**Comment by seanpbrandon** [comment]
I have moved all my devices to hubitat with the ring alarm integration and been on for about a month now. SmartThings was way more reliable with devices and controlling state. It would be nice to have this integration functioning again to go back to SmartThings.

**Comment by kolosy** [comment]
What I don't get is that this seems to be a breaking change in the Ring API, so it should have impacted the Hubitat integration too...

**Comment by seanpbrandon** [comment]
Hubitat is working perfectly exactly like SmartThings integration worked previously.

**Comment by ricklacy** [comment]
Not ideal, but I switched to using Amazon Alexa and the Simple Commands app. Works pretty well

**Comment by seanpbrandon** [comment]
You can’t disarm this method?

**Comment by ricklacy** [comment]
Yes, you can

**Comment by asishrs** [comment]
You can disarm by creating a custom command. Check https://community.ring.com/t/add-ability-to-arm-disarm-in-an-alexa-routine/9736

**Comment by kolosy** [comment]
I got this resolved for me and put up a PR if @asishrs is interested in merging it in. If not, people can either make the change themselves or use my fork. The tl;dr is that the api endpoint for the `Locations` call either changed or wasn't right to begin with and "just worked". Classic one line, one letter change but I'm back in business!

**Comment by asishrs** [comment]
thanks for your contribution. Release 3.4.1 is available now.
