### ISSUE TITLE
Ring Alarm Warning 

### ISSUE THREAD

**Issue by mbhforum** [asishrs/smartthings-ringalarmv2#9]
This is more of a feature request.  My house gets put into a specific mode which is supposed to Arm my Ring system, but there is a door open or motion being sensed and the Smartapp never arms the system.  It would be great if there was notification that the alarm was not armed for the reason and even give you the ability to bypass the warning and still arm the system.  if you manually go and arm the system in the Ring app, it does warn you and give you this opportunity.

**Comment by asishrs** [comment]
Thanks for your suggestion. I will look into this.

**Comment by music-tn** [comment]
First off, thanks so much for taking a shot at this and doing such a nice writeup!

I've recently been looking at the Ring Alarm, but won't commit unless I can figure out a way to integrate with smartThings.  This looks very promising, but the "arm warning" could be an issue in automations.  I've only just started looking at it, and I'm sure you're aware of [this integration](https://github.com/dgreif/ring-alarm) for HomeBridge.  I'm new to reading typeScript code, but I see in the setAlarmMode() function in the [alarm.ts](https://github.com/dgreif/ring-alarm/blob/master/api/alarm.ts) module that there's a second parameter for "bypassSensorZids".  It appears to be a String array of device zIDs.   I'm unsure, however, if that means to bypass those for alarm conditions, or if it means to bypass them for faults when setting the alarm.  If the latter, then perhaps there could be a function like "setAlarmIgnoreFaults" that passes **all** devices to the Status command when mode is set to 'all' or 'some' (i.e., ignore all faults) ?   Actually, I can't think of a good reason not to bypass all faults during an automation (by default), unless there's also a means by which to send a notification of the failure.

**Comment by music-tn** [comment]
I looked at the Ring Alarm help notes, and found the [description ](https://support.ring.com/hc/en-us/articles/360001173583-Bypassing-Devices) of how device bypass works.  If the API call works the same, then the interface code would need to:
- Create a list of sensors currently in "fault" mode
- Pass the list to the API when arming (as bypassSensorZids)

It isn't obvious from their description as to what happens if a door is open, you set the alarm and bypass it, and then exit through that door and close it?  When the timer expires, and the system arms, will it still bypass that sensor?  If so, that's a questionable design, imho.  There's also no mention of what happens when a person arms the system via a smart lock.  Their notes say you can arm using the lock keypad, but of course, there's no way for a lock to warn you of open sensors.   I assume that it just ignores faulted sensors, and proceeds with arming?

**Comment by mbhforum** [comment]
When there is a device fault (door open, motion detected) and you go to the Ring app and it asks for confirmation if you want to continue to arm the system.  Not sure if that is what your asking?

**Comment by music-tn** [comment]
@mbhforum:  I'm looking at it from a couple angles.  Per Ring FAQs, if you arm from the app, you get a notice to bypass.  If you arm from the Ring keypad, then you get a light, and you press the check.   In both cases, it precludes the faulted sensor(s) from monitoring, which seems odd.  I'd prefer the "check" approval be to bypass sensors that are still faulted *after* the timeout, rather than at the time of PIN entry, so that arming w/ a door open is possible, and then closing on the way out.  The other angle I was curious about is smart-lock integration (e.g., Schlage, etc).  Ring Alarm now supports using these to arm/disarm the system via keypad PIN entry, but there's no "notification" at the lock, and no mention of "bypassing sensors" in their FAQ.  I use one now w/ SmartThings and some CORE routines to control arm/disarm at the main door, and is used many times a day by family, and works great.

I just re-read your post at top, and see that my thoughts are a bit different.  I'm curious about an integration where a Ring "arm" command can be issued from ST, and have it **auto-bypass** faulted sensors.  For example, auto-arm at 11:15p w/o complaint.  If it's possible to issue a warning in the ST app showing faulted sensors at that time, then that would be consistent behavior w/ the way SHM currently does it.  SHM doesn't bypass faulted sensors, but does warn you w/ a popup message.  The sensors are still active though.

**Comment by asishrs** [comment]
I think this is doable. I need to figure the api params that I need to pass for this. Give me some time, i will dig into this.
